// Generated by CoffeeScript 1.7.1
var app, content, file, fs, io;

fs = require('fs');

content = require('node-static');

file = new content.Server;

app = require('http').createServer(function(request, response) {
  return request.addListener('end', function() {
    return file.serve(request, response);
  }).resume();
}).listen(8000);

io = require('socket.io').listen(8080);

io.sockets.on('connection', function(socket) {
  return socket.on('slideUpdate', function(data) {
    return socket.broadcast.emit('hashChange', {
      hash: data
    });
  });
});
